### ISSUE TITLE
ng serve throws a version warning

### ISSUE THREAD

**Issue by nerudaj** [CESNET/liberouter-gui#18]
move-modules branch throws following warning when ng serve is run:
```
@angular/compiler-cli@4.3.6 requires typescript@'>=2.1.0 <2.4.0' but 2.5.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.1.0 <2.4.0'

To disable this warning run "ng set --global warnings.typescriptMismatch=false".
```
Is it safe to use typescript 2.5.2?

**Comment by petrstehlik** [comment]
This happens when your global version of Angular-cli is different from the version which is installed in given project. Just upgrade your Angular-cli and all is fine.

`npm install @angular/cli@latest -g`

To be extra safe you should remove and install again whole `node_modules`.
