### ISSUE TITLE
Cannot create admin user with setup page

### ISSUE THREAD

**Issue by nerudaj** [CESNET/liberouter-gui#20]
If user database is empty and lgui switches to setup mode, admin user cannot be created. Submitting the form will throw an error:

`Response with status: 442 UNKNOWN for URL: http://192.168.56.101:4200/libapi/setup`

Due to new contributors to the project, this issue should be prioritized.

Here goes the error log of the server:
```
Caught error!
{'error': True, 'message': 'Session not found', 'status_code': 401}
127.0.0.1 - - [15/Sep/2017 17:59:27] "GET /authorization HTTP/1.1" 442 -
Caught error!
{'error': True, 'message': 'User not found', 'status_code': 404}
127.0.0.1 - - [15/Sep/2017 17:59:34] "POST /authorization HTTP/1.1" 442 -
Caught error!
{'error': True, 'message': {'error': "'dict' object has no attribute 'password'"}, 'status_code': 400}
127.0.0.1 - - [15/Sep/2017 17:59:41] "POST /setup HTTP/1.1" 442 -
```
I tried to examine the message headers and it seems that frontend sends correct data (JSON object with name, password and password2 keys).

**Comment by nerudaj** [comment]
@petrstehlik yesterday you had told me that dbConnector is stable for get/set operations and that GUI can be deployed, admin user registered and I can then log into the system. I have tried that right now and it is still impossible to create the admin user with the new backend error message:
```
Caught error!
{'message': {'error': "unhashable type: 'dict'"}, 'error': True, 'status_code': 400}
127.0.0.1 - - [15/Sep/2017 20:03:24] "POST /setup HTTP/1.1" 442 -
```

Could you please tag a commit with working version of the gui before this bug is fixed? Thanks

**Comment by petrstehlik** [comment]
Sorry for the inconvenience! The tip of the HEAD should be working: b1d46856713566c6c88553df245c837c9aa4fc84
