### ISSUE TITLE
Generating components with angular-cli in move-modules branch

### ISSUE THREAD

**Issue by nerudaj** [CESNET/liberouter-gui#21]
Using a command:
```sh
ng g component <name-of-component>
```

(and presumably all related generate commands) within any custom module will fail with error because `modules` folder is not a part of an angular project (defined by `.angular-cli.json`). There should be some dummy configuration file in `modules` folder that would allow using these generate commands.

**Comment by petrstehlik** [comment]
A dummy .angular-cli.json is not a wise idea. Using `ng g` command is just bootstrapping a component. If you really want this feature the easiest way is to create a proper .angular-cli.json for your module. This way you can develop quite easily the whole module. Using new modular system means isolating modules from the whole frontend framework therefore using any configuration from the base will probably be quite tricky to do automatically and the best way is to use your own head ;)
