### ISSUE TITLE
single device operation

### ISSUE THREAD

**Issue by jgroom33** [CESNET/liberouter-gui#48]
Current behavior:
liberouter can connect to multiple netconf servers

Desired behavior:
provide a set of environment variable that allow liberouter to connect to only 1 netconf device.
This behavior would eliminate user admin and the associated views

Use case:
Install and package liberouter directly on a netconf server to present a native UI for modify the server via a web interface

**Comment by rkrejci** [comment]
Hi, this is Netopeer2GUI specific, please raise the issue in its own issue tracker.

**Comment by jgroom33** [comment]
Thanks. I'll explore that option.
